image: php:7.3-fpm-alpine
variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - apk add --no-cache docker openssh freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev
  - docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1)
  - docker-php-ext-install -j${NPROC} gd
  - apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev
  - apk add --update-cache gnupg libzip-dev libxml2-dev git yarn bash php7-bcmath php7-pecl-amqp
  - docker-php-ext-install pdo_mysql xml mbstring json zip iconv ctype bcmath
  - set -xe
  - apk add --update icu
  - apk add --no-cache --virtual .php-deps make
  - apk add --no-cache --virtual .build-deps $PHPIZE_DEPS zlib-dev icu-dev g++
  - docker-php-ext-configure intl
  - docker-php-ext-install intl mysqli
  - docker-php-ext-enable intl mysqli && { find /usr/local/lib -type f -print0 | xargs -0r strip --strip-all -p 2>/dev/null || true; }
  - apk del .build-deps && rm -rf /tmp/* /usr/local/lib/php/doc/* /var/cache/apk/*
  - apk update && apk add -u yarn
  - echo "Install node js"
  - apk add --update nodejs nodejs-npm
  - echo "Install composer."
  - php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer
  - npm install -g npm
  - npm i -g pm2 typescript ts-node
cache:
  paths:
    - vendor/
    - none_modules/
stages:
  - stage
  - production
multiprokat-redesign-stage:
  stage: stage
  script:
    - echo "Deploy to staging server https://dev.multiprokat.com"
    - php composer install
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$AGENT_PRIVATE_SSH_KEY" | ssh-add -
    - ssh gitlab@95.216.203.131
  environment:
    name: staging
    url: https://dev.multiprokat.com
  tags:
    - multiprokat-redesign
  only:
    - develop
    - /^feature.*/
multiprokat-redesign-production:
  stage: production
  script:
    - echo "Deploy to production server https://dev.multiprokat.com"
  environment:
    name: production
    url: https://dev.multiprokat.com
  tags:
    - multiprokat-redesign
  only:
    - master
    - /^release\-\d+\.\d+\.\d+.*/
