image: php:7.3-fpm-alpine
variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  APP_ENV: prod
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: admin
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: multiprokat-redesign
  DATABASE_URL: mysql://admin:secret@mysql:3306/multiprokat-redesign
  GIT_SSL_NO_VERIFY: "true"
services:
  - mysql:latest

before_script:
  - apk add --no-cache docker openssh freetype wget libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev
  - docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1)
  - docker-php-ext-install -j${NPROC} gd
  - apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev
  - apk add --update-cache gnupg libzip-dev libxml2-dev git yarn bash php7-bcmath php7-pecl-amqp
  - docker-php-ext-install pdo_mysql xml mbstring json zip iconv ctype bcmath
  - set -xe
  - apk add --update icu
  - apk add --no-cache --virtual .php-deps make
  - apk add --no-cache --virtual .build-deps $PHPIZE_DEPS zlib-dev icu-dev g++
  - docker-php-ext-configure intl
  - docker-php-ext-install intl mysqli
  - docker-php-ext-enable intl mysqli && { find /usr/local/lib -type f -print0 | xargs -0r strip --strip-all -p 2>/dev/null || true; }
  - apk del .build-deps && rm -rf /tmp/* /usr/local/lib/php/doc/* /var/cache/apk/*
  - apk update && apk add -u yarn
  - echo "Install node js"
  - apk add --update nodejs nodejs-npm
  - npm install -g npm
  - npm i -g pm2 typescript ts-node
  - apk add --update --no-cache python-dev libffi-dev openssl-dev gcc libc-dev make py-pip && rm -rf /var/cache/apk/*
  - pip install docker-compose
  - docker-compose --version
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php --install-dir=bin --filename=composer
  - php bin/composer install
cache:
  paths:
    - vendor/
stages:
  - deploy

95.216.140.107:
  only:
    - develop
    - /^feature.*/
  stage: deploy
  script:
    # - php bin/console doctrine:schema:create
    - echo "DEPLOY to Stage Multiprokat-test"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$AGENT_PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh gitlab@95.216.140.107 "mkdir -p /var/www/multiprokat-redesign-temp"
    - scp -r * gitlab@95.216.140.107:/var/www/multiprokat-redesign-temp
    - ssh gitlab@95.216.140.107 "cp /var/www/environment/parameters.yml /var/www/multiprokat-redesign-temp/app/config/parameters.yml"
    - ssh gitlab@95.216.140.107 "mv /var/www/multiprokat-redesign /var/www/multiprokat-redesign_previous && mv /var/www/multiprokat-redesign-temp /var/www/multiprokat-redesign"
    - ssh gitlab@95.216.140.107 "sudo chown -R gitlab /var/www/multiprokat-redesign_previous && sudo chmod -R 777 /var/www/multiprokat-redesign/var/cache && rm -rf /var/www/multiprokat-redesign_previous && rm -rf /var/www/multiprokat-redesign-temp"
    - ssh gitlab@95.216.140.107 "sudo service nginx restart"
  tags:
    - multiprokat-redesign


