<?php

namespace AppBundle\Repository;

/**
 * CardPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
