<?php

namespace AppBundle\Repository;

/**
 * CardFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
