<?php

namespace AppBundle\Repository;

/**
 * CardFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
