<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountryTotal($country, $total){

        return $this ->createQueryBuilder('a')->
        andWhere('a.country = :country')->setParameter('country',$country)->
            andWhere('a.total > :total')->setParameter('total',$total)->getQuery()->getResult();

    }
}
