<?php

namespace AppBundle\Repository;

/**
 * DeletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeletedRepository extends \Doctrine\ORM\EntityRepository
{
}
