<?php

namespace AppBundle\Repository;

/**
 * FieldIntegerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldIntegerRepository extends \Doctrine\ORM\EntityRepository
{
}
