<?php

namespace AppBundle\Repository;

/**
 * GeneralTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
