<?php

namespace AppBundle\Repository;

/**
 * NotifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifyRepository extends \Doctrine\ORM\EntityRepository
{
}
