<?php

namespace AppBundle\Repository;

/**
 * SubFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
