<?php

namespace UserBundle\Repository;

/**
 * BlockingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockingRepository extends \Doctrine\ORM\EntityRepository
{
}
