<?php

namespace UserBundle\Repository;

/**
 * FormOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
