<?php

namespace UserBundle\Repository;

/**
 * TempActivated
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempActivatedRepository extends \Doctrine\ORM\EntityRepository
{
}
