<?php

namespace MarkBundle\Repository;

/**
 * CarCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarCharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
