<?php

namespace MarkBundle\Repository;

/**
 * CarCharacteristicValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarCharacteristicValueRepository extends \Doctrine\ORM\EntityRepository
{
}
