<?php

namespace MarkBundle\Repository;

/**
 * CarGenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarGenerationRepository extends \Doctrine\ORM\EntityRepository
{
}
