<?php

namespace MarkBundle\Repository;

/**
 * CarMarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarMarkRepository extends \Doctrine\ORM\EntityRepository
{
}
