<?php

namespace MarkBundle\Repository;

/**
 * CarModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarModificationRepository extends \Doctrine\ORM\EntityRepository
{
}
