<?php

namespace MarkBundle\Repository;

/**
 * CarSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
