<?php

namespace MarkBundle\Repository;

/**
 * CarTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
